# config/services.yaml
parameters:
    # Puedes definir aquí parámetros globales reutilizables si los necesitas

services:
    _defaults:
        autowire: true      # Symfony resolverá automáticamente las dependencias
        autoconfigure: true # Symfony aplicará automáticamente tags como controller.service_arguments, event_listener, etc.
        public: false       # Por default, todos los servicios son privados (buena práctica)

    # Exponer todos los servicios de src/ excepto lo que no deba ser tratado como servicio
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Repositorios de dominio (interface → implementación)
    App\Domain\Student\StudentRepositoryInterface:
        class: App\Infrastructure\Persistence\Doctrine\DoctrineStudentRepository

    # Application Services - Commands
    App\Application\Student\Command\CreateStudentCommandHandler:
        arguments:
            $studentRepository: '@App\Domain\Student\StudentRepositoryInterface'
            $entityManager: '@doctrine.orm.entity_manager'
            $passwordHasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'
            $eventDispatcher: '@event_dispatcher'
            $validator: '@validator'

    # Application Services - Queries
    App\Application\Student\Query\GetStudentByIdQueryHandler:
        arguments:
            $studentRepository: '@App\Domain\Student\StudentRepositoryInterface'

    App\Application\Student\Query\GetAllStudentsQueryHandler:
        arguments:
            $studentRepository: '@App\Domain\Student\StudentRepositoryInterface'

    # Event Listeners
    App\Infrastructure\EventListener\StudentCreatedEventListener:
        tags:
            - { name: kernel.event_listener, event: student.created, method: onStudentCreated }

    # Controllers (ya están autoconfigurados por default, pero explicitar el tag no está mal)
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

 