# config/services.yaml
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Make classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Domain Services
    App\Domain\Student\StudentRepositoryInterface:
        class: App\Infrastructure\Persistence\Doctrine\DoctrineStudentRepository

    # Application Services - Commands
    App\Application\Student\Command\CreateStudentCommandHandler:
        arguments:
            $studentRepository: '@App\Domain\Student\StudentRepositoryInterface'
            $entityManager: '@doctrine.orm.entity_manager'
            $passwordHasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'
            $eventDispatcher: '@event_dispatcher'
            $validator: '@validator'

    # Application Services - Queries
    App\Application\Student\Query\GetStudentByIdQueryHandler:
        arguments:
            $studentRepository: '@App\Domain\Student\StudentRepositoryInterface'

    App\Application\Student\Query\GetAllStudentsQueryHandler:
        arguments:
            $studentRepository: '@App\Domain\Student\StudentRepositoryInterface'

    # Event Listeners
    App\Infrastructure\EventListener\StudentCreatedEventListener:
        tags:
            - { name: kernel.event_listener, event: student.created, method: onStudentCreated }

    # Existing services
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
