doctrine_migrations:
    migrations_paths:
        # Namespace independiente para evitar autoload accidental
        'DoctrineMigrations': '%kernel.project_dir%/migrations'

    # No permitir el profiler en production (buena práctica)
    enable_profiler: false

    # Organización de carpetas por año (recomendado)
    organizing_migrations: true

    # Evita que se generen migraciones vacías por cambios irrelevantes de metadata
    check_database_platform: true
