nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers:
            - 'Content-Type'
            - 'Authorization'
            - 'Accept'
            - 'X-Requested-With'
        expose_headers:
            - 'Link'
            - 'X-RateLimit-Remaining'
            - 'X-RateLimit-Reset'
        max_age: 3600
        allow_credentials: true

    paths:
        '^/':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers:
                - 'Content-Type'
                - 'Authorization'
                - 'Accept'
                - 'X-Requested-With'
            expose_headers:
                - 'Link'
                - 'X-RateLimit-Remaining'
                - 'X-RateLimit-Reset'
            max_age: 3600
            allow_credentials: true
