services:
    oxford: &common
        build: .
        restart: on-failure
        env_file:
            - .oxford.env
        ports:
            - "8200:8000"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - app_storage:/var/www/html/storage/app
        post_start:
            - command:
                  [
                      "sh",
                      "-c",
                      "php artisan storage:link-uploads && php artisan storage:link",
                  ]
              user: nobody
volumes:
    app_storage:
